version: '3.9'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dev-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test-db
volumes:
  pgdata: {}